### ISSUE TITLE
加密了好像

### ISSUE THREAD

**Issue by blockboi-cyper** [choya-lee/hfutDailyCP#4]
各位同学，疫情信息收集模块有更新加密措施，可能会出现一些问题，请大家仔细查看是否完成，若出现问题建议大家清理今日校园缓存再试一试。请同学们抓紧时间打卡

**Comment by choya-lee** [comment]
今天已经成功打卡，而且刚才我又测试了一下，签到功能正常。请按照使用说明及进行设置，如有问题欢迎再次提出。
